name: microqa-action-workflow

on:
  push:
    branches:
      - "experiment"

jobs:
  measure:
    name: alvinwilta/microqa
    runs-on: ubuntu-latest

    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull docker image
        run: docker pull alvinwilta/microqa:latest

      - name: Run Docker image
        run: docker run -v "$(pwd):/app/robot-shop/" alvinwilta/microqa:latest -c "/app/robot-shop/microqa-config.yaml"
